_target_: src.models.diffusion.DDPM
# _partial_: True

defaults:
  - sampler: ddim.yaml
  - _self_

num_train_timesteps: 1000
image_size: 32
channels: 3
first_stage_key: image
conditional_stage_key: class
log_every_t: 10

sampler:
  beta_schedule: linear

model:
  _target_: src.models.unet.Unet
  in_channels: 3
  out_channels: 3
  hidden_channels: [128, 256, 256, 256]
  num_res_blocks: 2
  attn_type: standard
  attention_levels: [1]
  dropout: 0.1
  dim: 2
  channels_per_head: 32
  num_class_embeds: 10

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 2e-4
  # weight_decay: 0.0001

scheduler_config:
  scheduler:
    _target_: torch.optim.lr_scheduler.OneCycleLR
    _partial_: True
    max_lr: 2e-4
    total_steps: ${trainer.max_epochs}
  interval: epoch
