_target_: src.models.diffusion.DDPM
# _partial_: True

timesteps: 1000
image_size: 32
channels: 3
first_stage_key: image
learning_rate: 1e-4

unet:
  _target_: src.models.unet.Unet
  in_channels: 3
  out_channels: 3
  hidden_channels: [64, 128, 256, 256]
  num_res_blocks: 3
  attn:
    _target_: src.models.attention.EfficientAttention
  attention_levels: [0, 1, 2]
  dropout: 0.2
  dim: 2
  channels_per_head: 32
