_target_: src.models.diffusion.DDPM
# _partial_: True

timesteps: 1000
image_size: 32
channels: 1
first_stage_key: image
learning_rate: 1e-5

unet:
  _target_: src.models.unet.Unet
  in_channels: 1
  out_channels: 1
  hidden_channels: [64, 128]
  num_res_blocks: 2
  attn:
    _target_: src.models.attention.EfficientAttention
  attention_levels: [1]
  dropout: 0.2
  dim: 2
  channels_per_head: 32
